### ISSUE TITLE
Hello! You stole my code 🤗🤗🥰🥰😄

### ISSUE THREAD

**Issue by MoreFoxBeans** [Mathusalle/Test#1]
Hello there! 😀😃😄😊🤗🥰😄😊🤗🥰🥰 I noticed that you copied my code without giving me credit (😱😱😱) or making any modifications (😱😱😱😱😱), so kindly I ask you to either take it down or fork my original repo (🍴🍴) so that the code is linked back to me! Have a nice day! 🤗🤗🥰🥰🤗😀😃😄🤗🤗🥰🥰🤗🥰🥰🤗🤗😀😃😄😊🥰🥰🤗

My code: [@MoreFoxBeans/Pixel-84PCE/src/main.c](https://github.com/MoreFoxBeans/Pixel-84PCE/blob/main/src/main.c)

File in question: [@Mathusalle/Test/Test](https://github.com/Mathusalle/Test/blob/main/Test)

**Comment by Mathusalle** [comment]
sorry,

**Comment by Mathusalle** [comment]
I just well just... this is embarrassing, I was just trying out git for the first time sorry, I will give credit, sorry again.

**Comment by MoreFoxBeans** [comment]
Ok thank you!
